### ISSUE TITLE
Pushing logs out to file

### ISSUE THREAD

**Issue by Ic3Nine** [xmatters/xmtoolbox-quick-start#3]
I see the logLevel in config.js to control the detail but how do we save the logs from console to a file?

**Comment by brannonvann** [comment]
Hi @Ic3Nine,

You have a couple of options. 

1. You can leverage the `logPath` option to append an existing or non-existing file. You can read the full description here: [Environment Options](https://brannonvann.github.io/xmtoolbox/module-environments.html#.EnvironmentOptions ). This option includes timestamps but be aware that it appends the file given in the path so if you want to clear that file you will need to wipe it before you start.

2. You can access the output from the environment object like this `env.output.join('\n')`. In this example my environment is called `env` but this is often called `prod` or `np`.  The `output` key is an array so joining it with a new line character `\n` will give you normal log output.

**Comment by Ic3Nine** [comment]
Thanks for the prompt reply.   I created a date function that outputs yyyymmdd_hhmmss in backup.js.  just copied that over to config and use it to create unique log files.
