### ISSUE TITLE
Restore Shift issue

### ISSUE THREAD

**Issue by Ic3Nine** [xmatters/xmtoolbox-quick-start#4]
I've noticed an issue when restoring a rotationType:"Schedule" actually gets created as rotationType:"Shift".  I've tested this a couple of times by completely deleting the group after  backup and letting restore process re-create it.  The process completes successfully without any errors.  Has anyone come across this before?  Are we doing something incorrectly?

**Comment by brannonvann** [comment]
I haven't heard of this before but I'm happy to look at it. Do you have a set of reproduction steps you can supply that results in this issue?

**Comment by Ic3Nine** [comment]
1. Run backup.js
2.  Ensure rotation shows as  rotationType:'SCHEDULE" for desired shift in backup.json
3.  Delete group
4. Run restore.js
5. Check shift (shows up as rotation shift based).  Everything is restored properly, except the rotation type.

Everything in extractOptions in backup.js is default
Everything in syncOptions in restore.js is default

I can't post any snippets as we're blocked from posting to github from our corporate pcs.

**Comment by Ic3Nine** [comment]
OK.  Not sure what happened here but I'm going to go ahead and say this was on my end somewhere.  I just cleaned up all the backup files and tried again with a new set and the group restores properly.  not sure if restore was not picking up the proper file but I'm going to close this issue. Definitely pebkac somewhere.
