### ISSUE TITLE
Restore.js does not restore/update voice or sms devices

### ISSUE THREAD

**Issue by Ic3Nine** [xmatters/xmtoolbox-quick-start#5]
Apologies but I am not able to post logs or error messages from the console because github posting is disabled from corporate network.

Steps to reproduce

- Take backup
- Delete SMS and/or Voice device from any user
- Run restore.

The process fails with the error attached - https://i.imgur.com/jDcAA6p.png

This seems to only happen with voice and sms devices.  Also, I've tested with manually creating the deleted devices with different phone numbers.  In this case the restore goes through, but the phone numbers in the devices are incorrect.

**Comment by brannonvann** [comment]
Hi,

Thank you for supplying the steps to reproduce. Please install the latest xmtoolbox by using the command `npm install xmtoolbox` or install the specific version that has this fix by using `npm install xmtoolbox@1.2.5`.

-Brannon

**Comment by Ic3Nine** [comment]
Recreating missing devices is now working on latest xmtoolbox.  Thanks for the quick reply.
